// Generated by CoffeeScript 1.8.0
(function() {
  var fs, handler, request, service;

  request = require('request');

  fs = require('fs');

  service = 'http://informea.pops.int/Contacts2/brsContacts.svc/Contacts?&$select=brsContactRoleName&$format=json';

  handler = function(error, response, body) {
    var data, result, role, roles, row, v, values, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
    data = JSON.parse(body);
    roles = {};
    _ref = data['d'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      row = _ref[_i];
      _ref1 = row['brsContactRoleName'].split(',');
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        role = _ref1[_j];
        roles[role.trim()] = true;
      }
    }
    values = [];
    for (role in roles) {
      v = roles[role];
      values.push(role);
    }
    values.sort();
    result = [];
    for (_k = 0, _len2 = values.length; _k < _len2; _k++) {
      role = values[_k];
      result.push({
        'value': role
      });
    }
    fs.writeFile('roles.json', JSON.stringify(result, null, ' '));
  };

  request(service, handler);

}).call(this);
