// Generated by CoffeeScript 1.8.0
(function() {
  var OUTPUT, SERVICE, fs, handler, request;

  request = require('request');

  fs = require('fs');

  SERVICE = 'http://informea.pops.int/CountryProfiles/brsTreatyProfile.svc/countryNames?$select=NameEn,IsoCode2d&$format=json';

  OUTPUT = '../countries.json';

  handler = function(error, response, body) {
    var countries, data, row, _i, _len, _ref;
    data = JSON.parse(body);
    countries = [];
    _ref = data['d'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      row = _ref[_i];
      countries.push({
        "value": row["IsoCode2d"],
        "text": row["NameEn"]
      });
    }
    countries.sort(function(a, b) {
      if (a.text > b.text) {
        return 1;
      } else if (a.text < b.text) {
        return -1;
      }
      return 0;
    });
    fs.writeFile(OUTPUT, JSON.stringify(countries, null, ' '));
  };

  request(SERVICE, handler);

}).call(this);
