// Generated by CoffeeScript 1.8.0
(function() {
  var OUTPUT, SERVICE, fs, handler, request;

  request = require('request');

  fs = require('fs');

  SERVICE = 'http://informea.pops.int/MobileApp/brsMobileApp2.svc/Articles?$select=categories&$format=json';

  OUTPUT = '../app/json/news-categories.json';

  handler = function(error, response, body) {
    var c, categories, data, result, row, v, values, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;
    data = JSON.parse(body);
    categories = {};
    _ref = data['d']['results'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      row = _ref[_i];
      if (row['categories']) {
        _ref1 = row['categories'].split(',');
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          c = _ref1[_j];
          categories[c.trim()] = true;
        }
      }
    }
    values = [];
    for (c in categories) {
      v = categories[c];
      values.push(c);
    }
    values.sort();
    result = [];
    for (_k = 0, _len2 = values.length; _k < _len2; _k++) {
      c = values[_k];
      result.push({
        'value': c
      });
    }
    fs.writeFile(OUTPUT, JSON.stringify(result, null, ' '));
  };

  request(SERVICE, handler);

}).call(this);
